spring:
  application:
    name: gateway # \u2605 Eureka\uC5D0 \uB300\uBB38\uC790 'GATEWAY'\uB85C \uB4F1\uB85D\uB429\uB2C8\uB2E4.
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # Eureka\uC5D0 \uB4F1\uB85D\uB41C \uC11C\uBE44\uC2A4\uB4E4\uC744 \uC790\uB3D9\uC73C\uB85C \uB77C\uC6B0\uD305 (http://gateway/shop-service/...)
          lower-case-service-id: true
      routes:
        - id: coupon
          uri: lb://COUPON
          predicates:
            - Path=/coupons/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # \u2605 Eureka \uCEE8\uD14C\uC774\uB108 \uC774\uB984\uC774 'eureka'\uC774\uBBC0\uB85C \uC544\uB798\uC640 \uAC19\uC774 \uC124\uC815
      defaultZone: http://eureka:8761/eureka/