spring:
  application:
    name: team3-gateway


  data:
    redis:
      # .env의 REDIS_HOST 값 (기본값도 덮어씀)
      host: s4.java21.net
      # .env의 REDIS_PORT 값
      port: 6379
      # .env의 REDIS_PASS 값
      password: '*N2vya7H@muDTwdNMR!'
      # .env의 REDIS_DB 값
      database: 370

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  # docker-compose.yml의 JWT_SECRET 값
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLXNlY3JldC1rZXktZ2VuZXJhdGVkLWJ5LWJhc2U2NC1lbmNvZGVyLXRlc3QtMTIzNDU2Nzg5MA==
  # docker-compose.yml의 ACCESS_TOKEN_EXPIRATION 값
  expiration-time: 3600000
  token-prefix: Bearer
  header: Authorization

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

server:
  port: 8082