spring:
  application:
    name: team3-gateway

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
#          routes:
#                    - id: auth-route
#                      uri: lb://TEAM3-AUTH
#                      predicates:
#                        - Path=/auth/**

#                    - id: coupon-route
#                      uri: lb://TEAM3-COUPON
#                      predicates:
#                        - Path=/coupons/**
#
#                    - id: shop-route
#                      uri: lb://SHOP-SERVICE
#                      predicates:
#                        - Path=/shop-service/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always