server:
  port: 8080

spring:
  application:
    name: team3-gateway

  data:
    redis:
      host: localhost
      port: 6379
#      password: ${SPRING_DATA_REDIS_PASSWORD}
#      database: ${SPRING_DATA_REDIS_DATABASE}

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLXNlY3JldC1rZXktZ2VuZXJhdGVkLWJ5LWJhc2U2NC1lbmNvZGVyLXRlc3QtMTIzNDU2Nzg5MA==
  expiration-time: 3600000
  token-prefix: Bearer
  header: Authorization

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
